### ISSUE TITLE
i18n fallbacks not working starting 1.13

### ISSUE THREAD

**Issue by oleksii-leonov** [devise-i18n/devise-i18n#23]
After moving to Transifex in https://github.com/devise-i18n/devise-i18n/commit/145fbe051d54955bbd46c97c392345b0d5bfc30f, non-translated strings became empty strings `""` (instead of `nil` in the past).

For example, `bg.yml`:

Before:
```yaml
bg:
  activerecord:
    attributes:
      user:
        confirmation_sent_at:
        confirmation_token:
        confirmed_at:
        created_at:
        current_password: Настояща парола
```

After:
```yaml
bg:
  activerecord:
    attributes:
      user:
        confirmation_sent_at: ""
        confirmation_token: ""
        confirmed_at: ""
        created_at: ""
        current_password: Настояща парола
```

For non-translated strings, we use the `en` locale as a fallback in Rails.

- In devise-i18n 1.12, it works properly, and the User will see the string from the `en` locale if translation is not available.
- But since devise-i18n 1.13, non-translated strings became empty strings `""`, so fallback is not working, and an empty string is shown to the user.
